# docker-compose.yaml
version: '3.7'

services:
  # Database
  db:
    image: mysql:latest
    volumes:
      - ./db_data:/var/lib/mysql
    restart: always
    env_file: env/db.env
    ports:
      - '3306:3306'
    networks:
      - wpsite
  # phpmyadmin
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - '8080:80'
    env_file: env/phpmyadmin.env
    environment:
      PMA_HOST: db
    networks:
      - wpsite
  # Wordpress
  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    ports:
      - '8000:80'
    restart: always
    volumes:
      - ./src:/var/www/html
    environment:
      WORDPRESS_DB_HOST: db:3306
    env_file: env/wordpress.env
    networks:
      - wpsite
networks:
  wpsite:
volumes:
  db_data:
